### PR TITLE
Change power descriptions and their presentation

### LINKED ISSUE #484: DRAIN "into" description is odd
Drain 2d6 `into` SPD (20 Active Points); OAF (-1), OAF (-1), No STR Bonus (-1/2).  Is this a 5e TRANSFER leftover?  The word `into` should not be here.  Looks to be associated with (the yet to be release) 3.0.53 as this does not seem to be an issue with 3.0.52.

image

image

### PR DESCRIPTION
**Pull request by phBalance**
* Make adjustment power descriptions better with regards to _into_ and _from_
* Stop stripping out words from descriptions as it can lead to weird truncated descriptions. They aren't, magically, perfect of course but they should all have the power name in them now.
* Resolves #484

### CODE REVIEW

**Comment by aeauseth** [comment]
There is an extra `Blast` in the description

image
image
image

**Comment by aeauseth** [comment]
Extra TF.

image
image

**Comment by phBalance** [comment]
The descriptions are all being generated correctly. Will figure out where else the extra stuff is being added in.

**Comment by phBalance** [comment]
I think it's looking better now:
image
image

as well this offender looks better (but still not perfect):
image
image

**Pull request merged**
