### PR TITLE
reworking HeroRuler to extend Ruler

### PR DESCRIPTION
**Pull request by dmdorman**
Reworking HeroRuler to extend the base Ruler class

### CODE REVIEW

**Comment by aeauseth** [comment]
I'm sorta stilling your thunder here as I just reworked HeroRuler.mjs to EXTEND CONFIG.Canvas.rulerClass.  This part of a FoundryVTT v12 and DragRuler support.  Still working with the DragRuler guy to fix some problems, but you may not need this PR.

**Comment by dmdorman** [comment]
no worries, should I delete this PR then?

**Comment by aeauseth** [comment]
This is so out of date.  I think this PR should be closed/abandoned.

**Comment by dmdorman** [comment]
my bad, thought this was already closed

**Pull request closed without merging**
