### PR TITLE
Replace item.system.characteristic with item.system.CHARACTERISTIC

### LINKED ISSUE #511: Unable to change skill characteristic
3.0.53 preview

image

Notice characteristic change from PRE to GENERAL but the item in the skills tab still shows PRE.

### PR DESCRIPTION
**Pull request by phBalance**
Resolves #511 
* remove use of `item.system.characteristic` in code in favour of `item.system.CHARACTERISTIC`
* add migration function to change all items
* small cleanup of dead upload code

### CODE REVIEW

**Comment by aeauseth** [comment]
getAllActorsInGame only return actors, which is great.  There are places in the migration.js that check for actorLink, which I don't believe is necessary (line 226, 257,  288, for example).  Looks likely you only used getAllActorsInGame  in the newer migration stuff, which is fine.

**Comment by aeauseth** [comment]
migrate_from_3_0_49_to_3_0_53 is misleading it likely is migration 3.0.52 to 3.0.53.  I suggest removing the FROM and leaving the TO.  Not every release version needs migration.

**Comment by aeauseth** [comment]
Instead of setting characteristic = undefined, remove it entirely.  There is a hard to find (possibly undocumented) way to do this:

```js
await item.update({
    "item.system.CHARACTERISTIC":
        item.system.characteristic.toUpperCase(),
    "item.system.-=characteristic": null,
});
```

see actorj.s line 1194 for a working example.
```js
changes[`system.characteristics.-=${key}`] = null;
```

**Comment by aeauseth** [comment]
I see you made changes to upload_hdc.js.  I've slowly been moving code from upload_hdc.js to actor&item.js.  My plan was to delete upload_hdc.js at some point.  I think there are functions in upload_hdc.js that are no longer used (I moved them to actor/item but never commented them out).  Ya, my bad.

**Comment by phBalance** [comment]
> migrate_from_3_0_49_to_3_0_53 is misleading it likely is migration 3.0.52 to 3.0.53. I suggest removing the FROM and leaving the TO. Not every release version needs migration.

Was working with the assumption that the last release that had anything new that needed to be migrated seems to have been 3.0.49 hence the from and to. I have no issue with removing the from bit.

**Comment by phBalance** [comment]
> Instead of setting characteristic = undefined, remove it entirely. There is a hard to find (possibly undocumented) way to do this:
> 
> ```js
> await item.update({
>     "item.system.CHARACTERISTIC":
>         item.system.characteristic.toUpperCase(),
>     "item.system.-=characteristic": null,
> });
> ```
> 
> see actorj.s line 1194 for a working example.
> 
> ```js
> changes[`system.characteristics.-=${key}`] = null;
> ```
> 
> I' do not think that `delete item.system.characteristic;` updates the database.

Thanks for the hint. The intention was to remove it from the database by setting it to undefined. With a bit more testing I've also realized that I don't need to actually update system.CHARACTERISTICS as it appears the database changes get propagated back to the `system` values.

**Pull request merged**
